services:
  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: ghcr.io/nginxinc/nginx-unprivileged:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
