version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf" 