services:
  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    expose:
      - "8000"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend

volumes:
  pgdata:
