version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
