# Generated by Django 5.2 on 2025-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='football_competitions',
            field=models.BooleanField(default=False, verbose_name='Участвовали ли в соревнованиях?'),
        ),
        migrations.AddField(
            model_name='user',
            name='football_experience',
            field=models.CharField(blank=True, choices=[('newbie', 'Менее года'), ('amateur', '1-3 года'), ('regular', '3-5 лет'), ('pro', 'Более 5 лет')], max_length=20, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='user',
            name='football_formats',
            field=models.CharField(blank=True, choices=[('3x3', '3 на 3'), ('4x4', '4 на 4'), ('5x5', '5 на 5'), ('6x6', '6 на 6'), ('7x7', '7 на 7'), ('8x8', '8 на 8'), ('9x9', '9 на 9'), ('10x10', '10 на 10'), ('11x11', '11 на 11')], max_length=10, verbose_name='Формат игры (5Х5, 7Х7 и т.д.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='football_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Вообще не играю'), ('yearly', 'Несколько раз в год'), ('monthly', 'Несколько раз в месяц'), ('weekly', 'Несколько раз в неделю')], max_length=20, null=True, verbose_name='Частота игры'),
        ),
        migrations.AddField(
            model_name='user',
            name='football_position',
            field=models.CharField(blank=True, choices=[('gk', 'Вратарь'), ('def', 'Защитник'), ('mid', 'Полузащитник'), ('fwd', 'Нападающий')], max_length=10, null=True, verbose_name='Позиция (вратарь, защитник и т.д.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/avatar', verbose_name='Фотография'),
        ),
    ]
