# Generated by Django 5.2 on 2025-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='user', max_length=20),
        ),
    ]
