# Generated by Django 5.2 on 2025-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_first_name_user_telegram_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/profile/', verbose_name='Фотография'),
        ),
    ]
