# Generated by Django 5.2 on 2025-07-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
    ]
