# Generated by Django 5.2 on 2025-09-06 07:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('playgrounds', '0002_alter_region_options_remove_region_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=True, verbose_name='Приватный')),
                ('game_time', models.PositiveSmallIntegerField(choices=[(1, '1 час'), (2, '2 часа'), (3, '3 часа'), (4, '4 часа'), (5, '5 часов')], verbose_name='Время игры (часы)')),
                ('game_format', models.CharField(choices=[('3x3', '3 на 3'), ('4x4', '4 на 4'), ('5x5', '5 на 5'), ('6x6', '6 на 6'), ('7x7', '7 на 7'), ('8x8', '8 на 8'), ('9x9', '9 на 9'), ('10x10', '10 на 10'), ('11x11', '11 на 11')], default='5x5', max_length=5, verbose_name='Формат игры')),
                ('rounds', models.PositiveSmallIntegerField(default=1, verbose_name='Раундов')),
                ('location', models.CharField(default='Ташкент', editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='playgrounds.sportvenue', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('system_money', 'Система (баланс)'), ('click', 'Click'), ('cash', 'Наличные / Перевод')], default='system_money', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='bookings.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники события',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='bookings.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтвержено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('system_money', 'Система баллов/денег'), ('click', 'Click'), ('cash', 'Наличные/Перевод')], default='system_money', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.eventparticipant')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
