# Generated by Django 5.2 on 2025-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено'), ('COMPLETED', 'Завершено'), ('EXPIRED', 'Истекло')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
