# Generated by Django 5.2 on 2025-09-06 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_event_eventparticipant_event_participants_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_game_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 8, 41, 44, 435248, tzinfo=datetime.timezone.utc), verbose_name='Время начала игры'),
        ),
    ]
