# Generated by Django 5.2 on 2025-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='close_time',
            field=models.TimeField(default='23:00', verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Залоговая сумма'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_lights',
            field=models.BooleanField(default=False, verbose_name='Освещение'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_lockers',
            field=models.BooleanField(default=False, verbose_name='Раздевалки'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_restrooms',
            field=models.BooleanField(default=False, verbose_name='Туалеты'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_showers',
            field=models.BooleanField(default=False, verbose_name='Душевые'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='has_walls',
            field=models.BooleanField(default=False, verbose_name='Ограждение/стены'),
        ),
        migrations.AddField(
            model_name='sportvenue',
            name='open_time',
            field=models.TimeField(default='08:00', verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='sportvenuetype',
            name='is_indoor',
            field=models.BooleanField(default=False, verbose_name='Закрытое помещение'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sportvenue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='sportvenue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='sportvenue',
            name='yandex_map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Яндекс Карты'),
        ),
        migrations.AlterField(
            model_name='sportvenuetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
