# Generated by Django 5.2 on 2025-07-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportvenue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Спортивная площадка', 'verbose_name_plural': 'Спортивные площадки'},
        ),
    ]
