# Generated by Django 5.2 on 2025-07-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0002_alter_sportvenue_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportvenuetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sportvenuetype',
            name='icon',
        ),
    ]
