# Generated by Django 5.2 on 2025-05-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0004_favoriteplayground'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='playground_type_icons/', verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип поля',
                'verbose_name_plural': 'Типы полей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='playground',
            name='type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('FOOTBALL', 'Футбол'),
                    ('BASKETBALL', 'Баскетбол'),
                    ('TENNIS', 'Теннис'),
                    ('VOLLEYBALL', 'Волейбол'),
                    ('OTHER', 'Другое'),
                ],
                default='FOOTBALL',
                verbose_name='Тип поля',
                null=True,
                blank=True
            ),
        ),
    ]
