# Generated by Django 5.2 on 2025-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0005_playgroundtype_alter_playground_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='playground',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
