# Generated by Django 5.2 on 2025-05-30 16:30

from django.db import migrations, models

def copy_type_to_old_type(apps, schema_editor):
    Playground = apps.get_model('playgrounds', 'Playground')
    for playground in Playground.objects.all():
        playground.old_type = playground.type
        playground.save()

class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0006_playground_latitude_playground_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='old_type',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        migrations.RunPython(copy_type_to_old_type),
    ]
