# Generated by Django 5.2 on 2025-05-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0006_playground_latitude_playground_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playgrounds', to='playgrounds.playgroundtype', verbose_name='Тип поля'),
        ),
    ]
