# Generated by Django 5.2 on 2025-05-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0007_auto_20250530_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='old_type',
        ),
        migrations.AddField(
            model_name='playground',
            name='yandex_map_url',
            field=models.URLField(blank=True, help_text='Ссылка на место в Яндекс Картах', max_length=500, null=True, verbose_name='Ссылка на Яндекс Карты'),
        ),
    ]
