# Generated by Django 5.2 on 2025-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0007_auto_20250530_2130'),
    ]

    operations = [
    ]
