# Generated by Django 5.2 on 2025-05-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0007_alter_playground_type'),
        ('playgrounds', '0008_alter_playground_type'),
    ]

    operations = [
    ]
