# Generated by Django 5.2 on 2025-05-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0008_auto_20250530_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='old_type',
        ),
        migrations.AlterField(
            model_name='playground',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playgrounds', to='playgrounds.playgroundtype', verbose_name='Тип поля'),
        ),
    ]
