# Generated by Django 5.2 on 2025-05-30 16:31

from django.db import migrations

def convert_type_to_fk(apps, schema_editor):
    Playground = apps.get_model('playgrounds', 'Playground')
    PlaygroundType = apps.get_model('playgrounds', 'PlaygroundType')
    type_mapping = {
        'FOOTBALL': 'Футбол',
        'BASKETBALL': 'Баскетбол',
        'TENNIS': 'Теннис',
        'VOLLEYBALL': 'Волейбол',
        'OTHER': 'Другое'
    }
    for playground in Playground.objects.all():
        if playground.old_type:
            new_type_name = type_mapping.get(playground.old_type)
            if new_type_name:
                try:
                    new_type = PlaygroundType.objects.get(name=new_type_name)
                    playground.type = new_type
                    playground.save()
                except PlaygroundType.DoesNotExist:
                    pass

class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0009_remove_playground_old_type_alter_playground_type'),
    ]

    operations = [
        migrations.RunPython(convert_type_to_fk),
    ]
